### ISSUE TITLE
Is the zegformer trained in an inductive zero shot setting?

### ISSUE THREAD

**Issue by Genie-Kim** [dingjiansw101/ZegFormer#10]
Thanks for the good research.

I have a question about your paper.
As far as I know, there are inductive settings and transductive settings for the zero-shot task.
In the zero-shot classification task, the inductive setting can be clearly implemented, but in the ZS3 (zero-shot semantic segmentation) task, in the training stage, I know that the part corresponding to the unseen class in the input image is used without masking.

So I'm confused whether the ZegFormer is inductive or transductive setting.
In the case of zegformer, does it belong to inductive setting in ZS3 task?

**Comment by dingjiansw101** [comment]
I think it is still inductive in our ZegFormer setting, since the loss on unseen areas are ignored. That means, we only use the pixels belong to the seen classes for training. 
I know some methods generate the pseudo labels on the unseen areas and re-train the models (self-training). I think they are more close to the transductive setting.

**Comment by Genie-Kim** [comment]
I really appreciate your clear explanation.
Thank you.

**Comment by ZhengLeon** [comment]
@dingjiansw101 Hi, thanks for your great job.
If the input of the backbone contains the unseen class pixels during training?

**Comment by dingjiansw101** [comment]
It may contain the unlabelled pixels of unseen classes during training. It may also not contain.

**Comment by ZhengLeon** [comment]
Thanks for your kind respond.

If the pixels of unseen classes are unlabeled and used in the input of backbone, then how to get the ground truth of the mask loss?
